setwd("/Users/Eduardo Lisboa/Desktop/Programação/Segundo Período/Huffman")
ABBvsAVL <- read.table("ABBvsAVL.txt", header=TRUE)
attach(ABBvsAVL)
plot(VALOR, ABB, type="l", col="blue", ann=FALSE)
lines(VALOR, AVL, type="l", col="red")
title(main="ABB vs AVL", col.main="red", font.main=4)
title(xlab="Numero", col.lab=rgb(0,0.5,0))
title(ylab="Quantidade de comparações", col.lab=rgb(0,0.5,0))
legend("topright", legend=c("ABB", "AVL"), col=c("blue","red"), lty=1, lwd=2)
legend("topleft", c("Max ABB","Max AVL", "Min ABB", "Min AVL", max(ABB), max(AVL), min(ABB), min(AVL)), cex=0.8, ncol = 2)